import { CreatorCreativeModelOutputKind } from './constants';
import type { CreatorCreativeModelCapability } from './types';

export const CREATOR_CREATIVE_MODEL_CAPABILITIES: CreatorCreativeModelCapability[] = [
  {
    id: 'seedream-image',
    providerId: 'bytedance',
    displayName: 'Seedream Image',
    outputKinds: [CreatorCreativeModelOutputKind.Image],
    supportsVision: true,
    supportsReferenceImages: true,
    supportsBatch: true,
    recommendedFor: ['reference-image', 'product-visual', 'campaign-key-visual'],
    sizes: ['1:1', '4:5', '16:9'],
    maxBatchTasks: 24,
    costUnitLabel: 'image task',
    costUnitEstimate: 1,
  },
  {
    id: 'gpt-image',
    providerId: 'openai-compatible',
    displayName: 'GPT Image',
    outputKinds: [CreatorCreativeModelOutputKind.Image],
    supportsVision: true,
    supportsReferenceImages: true,
    supportsBatch: true,
    recommendedFor: ['prompt-faithfulness', 'layout', 'text-rendering'],
    sizes: ['1:1', '4:5', '3:2', '16:9'],
    maxBatchTasks: 16,
    costUnitLabel: 'image task',
    costUnitEstimate: 1,
  },
  {
    id: 'seedance-video',
    providerId: 'bytedance',
    displayName: 'Seedance Video',
    outputKinds: [CreatorCreativeModelOutputKind.Video],
    supportsVision: true,
    supportsReferenceImages: true,
    supportsBatch: false,
    recommendedFor: ['motion-concept', 'short-video'],
    sizes: ['16:9', '9:16', '1:1'],
    maxBatchTasks: 4,
    costUnitLabel: 'video task',
    costUnitEstimate: 4,
  },
  {
    id: 'prompt-only-review',
    providerId: 'local',
    displayName: 'Prompt Review',
    outputKinds: [CreatorCreativeModelOutputKind.Text],
    supportsVision: false,
    supportsReferenceImages: false,
    supportsBatch: true,
    recommendedFor: ['copy-check', 'direction-review'],
    sizes: ['text'],
    maxBatchTasks: 48,
    costUnitLabel: 'review task',
    costUnitEstimate: 0,
  },
];
